### ISSUE TITLE
race condition with loader when multiple charts on the same page

### ISSUE THREAD

**Issue by duanefields** [rakannimer/react-google-charts#197] opened 2018-05-18 21:10 UTC
If I have two charts on the same page, in different components, I get an error loading the second one, which doesn't appear.

Google Charts loader.js can only be loaded once

I'm assuming this is a race condition where they both start loading, then the second one bombs because the first one wins. Is there a general strategy for avoiding this issue?

**Comment by duanefields** [comment] 2018-05-18 21:43
It looks like isLoading never gets set to true, so it just tries to load the script again.

**Comment by oehm-smith** [comment] 2018-05-19 00:55
Dupe of #195

**Comment by duanefields** [comment] 2018-05-21 15:14
Fixed by https://github.com/rakannimer/react-google-charts/pull/199

**Closed** 2018-05-26 07:11 UTC

**Comment by FabianSchuessler** [comment] 2018-05-27 13:50
This issue was only fixed for multiple charts on one page.
The issue still persists for charts on different pages.
